// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Models;

#nullable disable

namespace StudyBuddy.Migrations
{
    [DbContext(typeof(StudyBuddyDBContext))]
    [Migration("20250728064513_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("StudyBuddy.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FavoriteID");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AnswerID");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QuestionID");

                    b.Property<string>("UserId")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserID");

                    b.HasKey("FavoriteId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("StudyBuddy.Models.QuestionsAndAnswer", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("QuestionID");

                    b.Property<string>("Answers")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Questions")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8C31A4CDE3");

                    b.ToTable("QuestionsAndAnswers");
                });

            modelBuilder.Entity("StudyBuddy.Models.Favorite", b =>
                {
                    b.HasOne("StudyBuddy.Models.QuestionsAndAnswer", "Answer")
                        .WithMany("FavoriteAnswers")
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("FK__Favorites__Answe__70DDC3D8");

                    b.HasOne("StudyBuddy.Models.QuestionsAndAnswer", "Question")
                        .WithMany("FavoriteQuestions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Favorites__Quest__6FE99F9F");

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StudyBuddy.Models.QuestionsAndAnswer", b =>
                {
                    b.Navigation("FavoriteAnswers");

                    b.Navigation("FavoriteQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
